[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
lottery = "49C48RyqUBFSv8RtMA6akJTAkKs2swHeARqA2wkmRWdJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
